import type { RankedProject, Category, Tag } from "@/types";

const CATEGORIES: Category[] = [
  { id: "1", name: "AI Agent", slug: "ai-agent", icon: "🤖", color: "#10b981", sortOrder: 1, projectCount: 42 },
  { id: "2", name: "LLM & Models", slug: "llm-models", icon: "🧠", color: "#f59e0b", sortOrder: 2, projectCount: 38 },
  { id: "3", name: "Developer Tools", slug: "dev-tools", icon: "🛠️", color: "#3b82f6", sortOrder: 3, projectCount: 56 },
  { id: "4", name: "Infrastructure", slug: "infrastructure", icon: "⚙️", color: "#8b5cf6", sortOrder: 4, projectCount: 31 },
  { id: "5", name: "Web Framework", slug: "web-framework", icon: "🌐", color: "#06b6d4", sortOrder: 5, projectCount: 27 },
  { id: "6", name: "Data & Analytics", slug: "data-analytics", icon: "📊", color: "#ec4899", sortOrder: 6, projectCount: 24 },
  { id: "7", name: "Security", slug: "security", icon: "🔒", color: "#ef4444", sortOrder: 7, projectCount: 19 },
  { id: "8", name: "Mobile", slug: "mobile", icon: "📱", color: "#14b8a6", sortOrder: 8, projectCount: 15 },
  { id: "9", name: "DevOps & Cloud", slug: "devops-cloud", icon: "☁️", color: "#6366f1", sortOrder: 9, projectCount: 22 },
  { id: "10", name: "NLP", slug: "nlp", icon: "💬", color: "#f97316", sortOrder: 10, projectCount: 18 },
  { id: "11", name: "Computer Vision", slug: "computer-vision", icon: "👁️", color: "#84cc16", sortOrder: 11, projectCount: 14 },
  { id: "12", name: "Automation", slug: "automation", icon: "⚡", color: "#eab308", sortOrder: 12, projectCount: 20 },
];

const TAGS: Tag[] = [
  { id: "t1", name: "TypeScript", slug: "typescript", color: "#3178c6" },
  { id: "t2", name: "Python", slug: "python", color: "#3776ab" },
  { id: "t3", name: "Rust", slug: "rust", color: "#dea584" },
  { id: "t4", name: "Go", slug: "go", color: "#00add8" },
  { id: "t5", name: "Open Source", slug: "open-source", color: "#22c55e" },
  { id: "t6", name: "AI/ML", slug: "ai-ml", color: "#f59e0b" },
  { id: "t7", name: "CLI", slug: "cli", color: "#a3a3a3" },
  { id: "t8", name: "API", slug: "api", color: "#06b6d4" },
];

function generateSparkline(base: number, days: number = 14): number[] {
  const data: number[] = [];
  let current = base;
  for (let i = 0; i < days; i++) {
    current += Math.floor(Math.random() * 200 - 50);
    if (current < 0) current = 0;
    data.push(current);
  }
  return data;
}

export const MOCK_PROJECTS: RankedProject[] = [
  {
    id: "1", source: "github", sourceId: "XiaomiMiMo/MiMo-Code", slug: "xiaomimimo-mimo-code",
    name: "MiMo-Code", fullName: "XiaomiMiMo/MiMo-Code",
    description: "An advanced AI coding agent from Xiaomi that leverages reinforcement learning to deliver state-of-the-art code generation, editing, and debugging capabilities.",
    sourceUrl: "https://github.com/XiaomiMiMo/MiMo-Code", primaryLanguage: "TypeScript", license: "Apache-2.0",
    ownerName: "XiaomiMiMo", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/186663390", ownerType: "org",
    topics: ["ai-agent", "coding-assistant", "reinforcement-learning"],
    stars: 14200, forks: 890, openIssues: 34, watchers: 312, contributorsCount: 28,
    createdAt: "2026-06-10T11:52:41Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2026-06-10T11:52:41Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 1, score: 98.7, starsGained: 1340, forksGained: 104,
    velocityScore: 95.2, momentumScore: 98.7,
    categories: [CATEGORIES[0], CATEGORIES[2]], tags: [TAGS[0], TAGS[5]],
    sparklineData: generateSparkline(1340),
  },
  {
    id: "2", source: "github", sourceId: "addyosmani/agent-skills", slug: "addyosmani-agent-skills",
    name: "agent-skills", fullName: "addyosmani/agent-skills",
    description: "Production-grade engineering skills for AI coding agents. A comprehensive collection of reusable skill modules.",
    sourceUrl: "https://github.com/addyosmani/agent-skills", primaryLanguage: "Shell", license: "MIT",
    ownerName: "addyosmani", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/110953", ownerType: "user",
    topics: ["ai-agent", "ai-skills", "coding-assistant"],
    stars: 8690, forks: 790, openIssues: 12, watchers: 210, contributorsCount: 45,
    createdAt: "2026-02-15T20:20:26Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2026-02-15T20:20:26Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 2, score: 92.1, starsGained: 869, forksGained: 79,
    velocityScore: 88.5, momentumScore: 92.1,
    categories: [CATEGORIES[0]], tags: [TAGS[5], TAGS[4]],
    sparklineData: generateSparkline(869),
  },
  {
    id: "3", source: "github", sourceId: "apple/container", slug: "apple-container",
    name: "container", fullName: "apple/container",
    description: "A tool for creating and running Linux containers using lightweight virtual machines on a Mac. Written in Swift, optimized for Apple silicon.",
    sourceUrl: "https://github.com/apple/container", primaryLanguage: "Swift", license: "Apache-2.0",
    ownerName: "apple", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/10639145", ownerType: "org",
    topics: ["containers", "linux", "macos", "swift", "apple-silicon"],
    stars: 26800, forks: 520, openIssues: 87, watchers: 890, contributorsCount: 34,
    createdAt: "2025-05-30T21:26:05Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2025-05-30T21:26:05Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 3, score: 89.4, starsGained: 687, forksGained: 34,
    velocityScore: 82.1, momentumScore: 89.4,
    categories: [CATEGORIES[3], CATEGORIES[8]], tags: [TAGS[4]],
    sparklineData: generateSparkline(687),
  },
  {
    id: "4", source: "github", sourceId: "shadcn/improve", slug: "shadcn-improve",
    name: "improve", fullName: "shadcn/improve",
    description: "Use your most capable model to audit your codebase and write plans for cheaper models to execute. An intelligent code improvement pipeline.",
    sourceUrl: "https://github.com/shadcn/improve", primaryLanguage: "TypeScript", license: "MIT",
    ownerName: "shadcn", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/124599", ownerType: "user",
    topics: ["ai-agent", "code-review", "developer-tools"],
    stars: 5200, forks: 310, openIssues: 8, watchers: 145, contributorsCount: 12,
    createdAt: "2026-06-10T11:06:58Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2026-06-10T11:06:58Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 4, score: 87.2, starsGained: 5200, forksGained: 310,
    velocityScore: 99.0, momentumScore: 87.2,
    categories: [CATEGORIES[2]], tags: [TAGS[0], TAGS[5]],
    sparklineData: generateSparkline(5200),
  },
  {
    id: "5", source: "github", sourceId: "harry0703/MoneyPrinterTurbo", slug: "harry0703-moneyprinterturbo",
    name: "MoneyPrinterTurbo", fullName: "harry0703/MoneyPrinterTurbo",
    description: "利用AI大模型，一键生成高清短视频 Generate short videos with one click using AI LLM.",
    sourceUrl: "https://github.com/harry0703/MoneyPrinterTurbo", primaryLanguage: "Python", license: "MIT",
    ownerName: "harry0703", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/3315573", ownerType: "user",
    topics: ["ai-video", "content-generation", "llm"],
    stars: 42100, forks: 5100, openIssues: 156, watchers: 620, contributorsCount: 67,
    createdAt: "2024-03-11T02:57:34Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2024-03-11T02:57:34Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 5, score: 85.0, starsGained: 542, forksGained: 89,
    velocityScore: 72.3, momentumScore: 85.0,
    categories: [CATEGORIES[1], CATEGORIES[11]], tags: [TAGS[1], TAGS[5]],
    sparklineData: generateSparkline(542),
  },
  {
    id: "6", source: "github", sourceId: "soxoj/maigret", slug: "soxoj-maigret",
    name: "maigret", fullName: "soxoj/maigret",
    description: "🕵️‍♂️ Collect a dossier on a person by username from 3000+ sites. OSINT tool for comprehensive username search.",
    sourceUrl: "https://github.com/soxoj/maigret", primaryLanguage: "Python", license: "MIT",
    ownerName: "soxoj", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/31013580", ownerType: "user",
    topics: ["osint", "security", "web-scraping", "username-search"],
    stars: 18500, forks: 1420, openIssues: 43, watchers: 320, contributorsCount: 89,
    createdAt: "2020-06-27T14:16:42Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2020-06-27T14:16:42Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 6, score: 82.3, starsGained: 478, forksGained: 56,
    velocityScore: 68.9, momentumScore: 82.3,
    categories: [CATEGORIES[6]], tags: [TAGS[1], TAGS[6]],
    sparklineData: generateSparkline(478),
  },
  {
    id: "7", source: "github", sourceId: "activeloopai/hivemind", slug: "activeloopai-hivemind",
    name: "hivemind", fullName: "activeloopai/hivemind",
    description: "One brain for all your agents. A unified memory and coordination layer for multi-agent systems.",
    sourceUrl: "https://github.com/activeloopai/hivemind", primaryLanguage: "JavaScript", license: "Apache-2.0",
    ownerName: "activeloopai", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/31466017", ownerType: "org",
    topics: ["ai-agent", "multi-agent", "memory"],
    stars: 3400, forks: 210, openIssues: 18, watchers: 98, contributorsCount: 15,
    createdAt: "2026-04-03T21:02:08Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2026-04-03T21:02:08Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 7, score: 79.8, starsGained: 412, forksGained: 38,
    velocityScore: 75.2, momentumScore: 79.8,
    categories: [CATEGORIES[0], CATEGORIES[3]], tags: [TAGS[5]],
    sparklineData: generateSparkline(412),
  },
  {
    id: "8", source: "github", sourceId: "FareedKhan-dev/train-llm-from-scratch", slug: "fareedkhan-train-llm",
    name: "train-llm-from-scratch", fullName: "FareedKhan-dev/train-llm-from-scratch",
    description: "A straightforward method for training your LLM, from downloading data to generating text. Complete educational resource.",
    sourceUrl: "https://github.com/FareedKhan-dev/train-llm-from-scratch", primaryLanguage: "Jupyter Notebook", license: "MIT",
    ownerName: "FareedKhan-dev", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/67846627", ownerType: "user",
    topics: ["llm", "machine-learning", "education", "nlp"],
    stars: 12300, forks: 1650, openIssues: 5, watchers: 280, contributorsCount: 8,
    createdAt: "2025-01-12T04:03:05Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2025-01-12T04:03:05Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 8, score: 77.5, starsGained: 389, forksGained: 67,
    velocityScore: 65.8, momentumScore: 77.5,
    categories: [CATEGORIES[1], CATEGORIES[9]], tags: [TAGS[1], TAGS[5]],
    sparklineData: generateSparkline(389),
  },
  {
    id: "9", source: "huggingface", sourceId: "deepseek-ai/DeepSeek-R2", slug: "deepseek-r2",
    name: "DeepSeek-R2", fullName: "deepseek-ai/DeepSeek-R2",
    description: "DeepSeek-R2: Next-generation reasoning model with enhanced chain-of-thought capabilities and 256K context window.",
    sourceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-R2", primaryLanguage: "Python", license: "Apache-2.0",
    ownerName: "deepseek-ai", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/148040998", ownerType: "org",
    topics: ["reasoning", "llm", "transformers"],
    stars: 0, forks: 0, openIssues: 0, watchers: 0, downloads: 2850000, contributorsCount: 12,
    createdAt: "2026-05-20T00:00:00Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2026-05-20T00:00:00Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 9, score: 76.1, starsGained: 0, forksGained: 0,
    velocityScore: 88.0, momentumScore: 76.1,
    categories: [CATEGORIES[1]], tags: [TAGS[1], TAGS[5]],
    sparklineData: generateSparkline(180000),
  },
  {
    id: "10", source: "github", sourceId: "anomalyco/opencode", slug: "anomalyco-opencode",
    name: "opencode", fullName: "anomalyco/opencode",
    description: "The open source coding agent. A terminal-based AI coding assistant with full codebase understanding.",
    sourceUrl: "https://github.com/anomalyco/opencode", primaryLanguage: "TypeScript", license: "MIT",
    ownerName: "anomalyco", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/196909847", ownerType: "org",
    topics: ["ai-agent", "coding-assistant", "terminal"],
    stars: 15800, forks: 620, openIssues: 45, watchers: 380, contributorsCount: 52,
    createdAt: "2025-04-30T20:08:00Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2025-04-30T20:08:00Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 10, score: 74.8, starsGained: 345, forksGained: 28,
    velocityScore: 62.1, momentumScore: 74.8,
    categories: [CATEGORIES[0], CATEGORIES[2]], tags: [TAGS[0], TAGS[6]],
    sparklineData: generateSparkline(345),
  },
  {
    id: "11", source: "github", sourceId: "hugohe3/ppt-master", slug: "hugohe3-ppt-master",
    name: "ppt-master", fullName: "hugohe3/ppt-master",
    description: "AI generates natively editable PPTX from any document — real PowerPoint shapes with native animations, not images.",
    sourceUrl: "https://github.com/hugohe3/ppt-master", primaryLanguage: "Python", license: "MIT",
    ownerName: "hugohe3", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/35719881", ownerType: "user",
    topics: ["ai-workflow", "document-processing", "powerpoint"],
    stars: 9200, forks: 430, openIssues: 22, watchers: 190, contributorsCount: 14,
    createdAt: "2025-12-10T06:54:33Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2025-12-10T06:54:33Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 11, score: 72.1, starsGained: 310, forksGained: 45,
    velocityScore: 58.4, momentumScore: 72.1,
    categories: [CATEGORIES[11]], tags: [TAGS[1], TAGS[5]],
    sparklineData: generateSparkline(310),
  },
  {
    id: "12", source: "github", sourceId: "chopratejas/headroom", slug: "chopratejas-headroom",
    name: "headroom", fullName: "chopratejas/headroom",
    description: "Compress tool outputs, logs, files, and RAG chunks before they reach the LLM. 60-95% fewer tokens, same answers.",
    sourceUrl: "https://github.com/chopratejas/headroom", primaryLanguage: "Python", license: "MIT",
    ownerName: "chopratejas", ownerAvatarUrl: "https://avatars.githubusercontent.com/u/13523450", ownerType: "user",
    topics: ["ai-agent", "token-optimization", "llm-tools"],
    stars: 4100, forks: 180, openIssues: 9, watchers: 112, contributorsCount: 7,
    createdAt: "2026-01-07T19:58:51Z", updatedAt: "2026-06-11T00:00:00Z",
    sourceCreatedAt: "2026-01-07T19:58:51Z", lastCrawledAt: "2026-06-11T07:00:00Z",
    rank: 12, score: 70.5, starsGained: 285, forksGained: 22,
    velocityScore: 55.7, momentumScore: 70.5,
    categories: [CATEGORIES[0], CATEGORIES[3]], tags: [TAGS[1], TAGS[5]],
    sparklineData: generateSparkline(285),
  },
];

export const MOCK_CATEGORIES = CATEGORIES;
export const MOCK_TAGS = TAGS;
